import type { Product } from "../types/product";

export const MOCK_PRODUCTS: Product[] = [
  // ===== BONÉS (8 produtos) =====
  {
    id: "p-001",
    idControl: "#BONE0001",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "bones",
    name: "Boné Country Trucker Premium",
    title: "Boné Country Trucker Premium",
    subtitle: "Aba curvada com bordado",
    description:
      "Boné trucker com tela traseira respirável e bordado frontal exclusivo. Perfeito para o dia a dia no estilo country.",
    quantity: 50,
    alert_stock: 5,
    status: "ACTIVE",
    price: 49.9,
    is_price_visible: true,
    brand: "No Limite do Laço",
    tags: ["boné", "trucker", "country", "bordado"],
    technical_specs: {
      material: "Algodão/Poliéster",
      aba: "Curvada",
      ajuste: "Snapback",
    },
    image: "/products/bone-01.svg",
    created_at: "2025-01-10T10:00:00Z",
    updated_at: "2025-01-10T10:00:00Z",
  },
  {
    id: "p-002",
    idControl: "#BONE0002",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "bones",
    name: "Boné Rodeio Aba Reta",
    title: "Boné Rodeio Aba Reta",
    subtitle: "Edição limitada",
    description:
      "Boné aba reta com design único de rodeio. Edição limitada com detalhes em relevo.",
    quantity: 30,
    alert_stock: 3,
    status: "ACTIVE",
    price: 59.9,
    is_price_visible: true,
    brand: "No Limite do Laço",
    tags: ["boné", "aba reta", "rodeio", "limitada"],
    technical_specs: {
      material: "Algodão 100%",
      aba: "Reta",
      ajuste: "Snapback",
    },
    image: "/products/bone-02.svg",
    created_at: "2025-01-10T10:00:00Z",
    updated_at: "2025-01-10T10:00:00Z",
  },
  {
    id: "p-003",
    idControl: "#BONE0003",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "bones",
    name: "Boné Tela Country Classic",
    title: "Boné Tela Country Classic",
    description:
      "Modelo clássico com tela traseira e frente estruturada. Ideal para revenda em atacado.",
    quantity: 120,
    alert_stock: 10,
    status: "ACTIVE",
    price: 34.9,
    is_price_visible: true,
    tags: ["boné", "tela", "classic", "atacado"],
    technical_specs: {
      material: "Poliéster/Tela",
      aba: "Curvada",
      ajuste: "Velcro",
    },
    image: "/products/bone-03.svg",
    created_at: "2025-02-05T10:00:00Z",
    updated_at: "2025-02-05T10:00:00Z",
  },
  {
    id: "p-004",
    idControl: "#BONE0004",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "bones",
    name: "Boné Western Bordado Cavalo",
    title: "Boné Western Bordado Cavalo",
    subtitle: "Bordado 3D premium",
    description:
      "Boné com bordado 3D de cavalo em alta definição. Acabamento premium para quem quer se destacar.",
    quantity: 0,
    alert_stock: 5,
    status: "ACTIVE",
    price: 69.9,
    is_price_visible: true,
    brand: "No Limite do Laço",
    tags: ["boné", "western", "bordado 3D", "premium"],
    technical_specs: {
      material: "Algodão/Poliéster",
      aba: "Curvada",
      bordado: "3D",
    },
    image: "/products/bone-04.svg",
    created_at: "2025-02-10T10:00:00Z",
    updated_at: "2025-02-10T10:00:00Z",
  },
  {
    id: "p-005",
    idControl: "#BONE0005",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "bones",
    name: "Boné Cowboy Vintage",
    title: "Boné Cowboy Vintage",
    description:
      "Estilo vintage com lavagem especial. Boné com aspecto envelhecido perfeito para looks despojados.",
    quantity: 45,
    alert_stock: 5,
    status: "ACTIVE",
    price: 44.9,
    is_price_visible: false,
    tags: ["boné", "vintage", "cowboy", "lavagem"],
    technical_specs: {
      material: "Algodão lavado",
      aba: "Curvada",
      ajuste: "Fivela",
    },
    image: "/products/bone-05.svg",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "p-006",
    idControl: "#BONE0006",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "bones",
    name: "Boné Country Kids",
    title: "Boné Country Kids",
    subtitle: "Infantil",
    description:
      "Boné country infantil com tamanho ajustável. Perfeito para os pequenos cowboys e cowgirls.",
    quantity: 80,
    alert_stock: 8,
    status: "ACTIVE",
    price: 29.9,
    is_price_visible: true,
    tags: ["boné", "infantil", "kids", "country"],
    technical_specs: {
      material: "Algodão",
      aba: "Curvada",
      tamanho: "Infantil ajustável",
    },
    image: "/products/bone-06.svg",
    created_at: "2025-03-05T10:00:00Z",
    updated_at: "2025-03-05T10:00:00Z",
  },
  {
    id: "p-007",
    idControl: "#BONE0007",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "bones",
    name: "Boné Rodeio Neon",
    title: "Boné Rodeio Neon",
    subtitle: "Coleção festival",
    description:
      "Boné com detalhes neon para festivais e rodeios. Destaque-se na multidão com cores vibrantes.",
    quantity: 35,
    alert_stock: 5,
    status: "ACTIVE",
    price: 54.9,
    is_price_visible: true,
    tags: ["boné", "neon", "festival", "rodeio"],
    technical_specs: { material: "Poliéster", aba: "Reta", ajuste: "Snapback" },
    image: "/products/bone-07.svg",
    created_at: "2025-03-10T10:00:00Z",
    updated_at: "2025-03-10T10:00:00Z",
  },
  {
    id: "p-008",
    idControl: "#BONE0008",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "bones",
    name: "Boné Ranch Life",
    title: "Boné Ranch Life",
    description:
      "Boné estilo ranch com estampa exclusiva. Conforto e estilo para o dia inteiro.",
    quantity: 60,
    alert_stock: 5,
    status: "DRAFT",
    price: 39.9,
    is_price_visible: true,
    tags: ["boné", "ranch", "fazenda"],
    technical_specs: {
      material: "Algodão/Poliéster",
      aba: "Curvada",
      ajuste: "Velcro",
    },
    image: "/products/bone-08.svg",
    created_at: "2025-03-15T10:00:00Z",
    updated_at: "2025-03-15T10:00:00Z",
  },

  // ===== CARTEIRAS (8 produtos) =====
  {
    id: "p-009",
    idControl: "#CART0001",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "carteiras",
    name: "Carteira Couro Legítimo Country",
    title: "Carteira Couro Legítimo Country",
    subtitle: "Couro bovino premium",
    description:
      "Carteira em couro bovino legítimo com detalhes de costura country. Compartimentos para cartões, notas e moedas.",
    quantity: 40,
    alert_stock: 5,
    status: "ACTIVE",
    price: 89.9,
    is_price_visible: true,
    brand: "No Limite do Laço",
    tags: ["carteira", "couro legítimo", "country", "masculina"],
    technical_specs: {
      material: "Couro bovino",
      compartimentos: 8,
      fechamento: "Bífold",
    },
    image: "/products/carteira-01.svg",
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "p-010",
    idControl: "#CART0002",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "carteiras",
    name: "Carteira Feminina Bordada",
    title: "Carteira Feminina Bordada",
    subtitle: "Com bordado floral country",
    description:
      "Carteira feminina com bordado floral em estilo country. Espaçosa e elegante.",
    quantity: 25,
    alert_stock: 3,
    status: "ACTIVE",
    price: 79.9,
    is_price_visible: true,
    tags: ["carteira", "feminina", "bordada", "floral"],
    technical_specs: {
      material: "Couro sintético",
      compartimentos: 10,
      fechamento: "Zíper",
    },
    image: "/products/carteira-02.svg",
    created_at: "2025-01-20T10:00:00Z",
    updated_at: "2025-01-20T10:00:00Z",
  },
  {
    id: "p-011",
    idControl: "#CART0003",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "carteiras",
    name: "Carteira Slim Rústica",
    title: "Carteira Slim Rústica",
    description:
      "Carteira slim com acabamento rústico. Perfeita para quem prefere praticidade sem perder o estilo.",
    quantity: 55,
    alert_stock: 5,
    status: "ACTIVE",
    price: 59.9,
    is_price_visible: true,
    tags: ["carteira", "slim", "rústica", "compacta"],
    technical_specs: {
      material: "Couro reciclado",
      compartimentos: 5,
      fechamento: "Bífold slim",
    },
    image: "/products/carteira-03.svg",
    created_at: "2025-02-01T10:00:00Z",
    updated_at: "2025-02-01T10:00:00Z",
  },
  {
    id: "p-012",
    idControl: "#CART0004",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "carteiras",
    name: "Carteira Porta-Celular Western",
    title: "Carteira Porta-Celular Western",
    subtitle: "2 em 1",
    description:
      "Carteira que também serve como porta-celular. Praticidade western no seu bolso.",
    quantity: 20,
    alert_stock: 3,
    status: "ACTIVE",
    price: 99.9,
    is_price_visible: false,
    brand: "No Limite do Laço",
    tags: ["carteira", "porta-celular", "western", "multifuncional"],
    technical_specs: {
      material: "Couro bovino",
      compartimentos: 6,
      "porta-celular": true,
    },
    image: "/products/carteira-04.svg",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: "2025-02-15T10:00:00Z",
  },
  {
    id: "p-013",
    idControl: "#CART0005",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "carteiras",
    name: "Carteira Corrente Country",
    title: "Carteira Corrente Country",
    subtitle: "Com corrente de segurança",
    description:
      "Carteira com corrente de segurança destacável. Estilo e segurança para o cowboy moderno.",
    quantity: 30,
    alert_stock: 5,
    status: "ACTIVE",
    price: 74.9,
    is_price_visible: true,
    tags: ["carteira", "corrente", "segurança", "country"],
    technical_specs: {
      material: "Couro sintético premium",
      corrente: "Metal envelhecido",
      compartimentos: 7,
    },
    image: "/products/carteira-05.svg",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "p-014",
    idControl: "#CART0006",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "carteiras",
    name: "Porta-Cartão Rodeio",
    title: "Porta-Cartão Rodeio",
    description:
      "Porta-cartão compacto com estampa de rodeio. Ideal para carregar apenas o essencial.",
    quantity: 70,
    alert_stock: 8,
    status: "ACTIVE",
    price: 34.9,
    is_price_visible: true,
    tags: ["porta-cartão", "rodeio", "compacto", "minimalista"],
    technical_specs: {
      material: "Couro sintético",
      compartimentos: 4,
      "porta-notas": false,
    },
    image: "/products/carteira-06.svg",
    created_at: "2025-03-10T10:00:00Z",
    updated_at: "2025-03-10T10:00:00Z",
  },
  {
    id: "p-015",
    idControl: "#CART0007",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "carteiras",
    name: "Carteira Trifold Cowboy",
    title: "Carteira Trifold Cowboy",
    subtitle: "Modelo trifold clássico",
    description:
      "Carteira no formato trifold com capacidade extra. Clássica e funcional.",
    quantity: 15,
    alert_stock: 3,
    status: "ACTIVE",
    price: 109.9,
    is_price_visible: true,
    brand: "No Limite do Laço",
    tags: ["carteira", "trifold", "cowboy", "clássica"],
    technical_specs: {
      material: "Couro bovino",
      compartimentos: 12,
      fechamento: "Trifold",
    },
    image: "/products/carteira-07.svg",
    created_at: "2025-03-15T10:00:00Z",
    updated_at: "2025-03-15T10:00:00Z",
  },
  {
    id: "p-016",
    idControl: "#CART0008",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "carteiras",
    name: "Carteira Infantil Ranch",
    title: "Carteira Infantil Ranch",
    subtitle: "Para pequenos cowboys",
    description:
      "Carteira infantil com estampa de rancho. Velcro fácil de abrir para crianças.",
    quantity: 0,
    alert_stock: 5,
    status: "ACTIVE",
    price: 24.9,
    is_price_visible: true,
    tags: ["carteira", "infantil", "ranch", "kids"],
    technical_specs: {
      material: "Nylon",
      compartimentos: 3,
      fechamento: "Velcro",
    },
    image: "/products/carteira-08.svg",
    created_at: "2025-03-20T10:00:00Z",
    updated_at: "2025-03-20T10:00:00Z",
  },

  // ===== CAMISAS (8 produtos) =====
  {
    id: "p-017",
    idControl: "#CAMI0001",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camisa Xadrez Country Masculina",
    title: "Camisa Xadrez Country Masculina",
    subtitle: "Manga longa flanelada",
    description:
      "Camisa xadrez flanelada com corte country. Confortável e estilosa para todas as ocasiões.",
    quantity: 60,
    alert_stock: 5,
    status: "ACTIVE",
    price: 129.9,
    is_price_visible: true,
    brand: "No Limite do Laço",
    tags: ["camisa", "xadrez", "flanela", "masculina"],
    technical_specs: {
      material: "Algodão flanelado",
      manga: "Longa",
      tamanhos: "P ao GG",
    },
    image: "/products/camisa-01.svg",
    created_at: "2025-01-05T10:00:00Z",
    updated_at: "2025-01-05T10:00:00Z",
  },
  {
    id: "p-018",
    idControl: "#CAMI0002",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camisa Country Feminina Bordada",
    title: "Camisa Country Feminina Bordada",
    subtitle: "Com bordado nas costas",
    description:
      "Camisa feminina em algodão com bordado country detalhado nas costas. Elegância com personalidade.",
    quantity: 35,
    alert_stock: 5,
    status: "ACTIVE",
    price: 149.9,
    is_price_visible: true,
    tags: ["camisa", "feminina", "bordada", "country"],
    technical_specs: {
      material: "Algodão premium",
      manga: "Longa",
      tamanhos: "PP ao G",
    },
    image: "/products/camisa-02.svg",
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "p-019",
    idControl: "#CAMI0003",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camisa Polo Western",
    title: "Camisa Polo Western",
    description:
      "Polo com detalhes western. Casual e confortável para o dia a dia.",
    quantity: 80,
    alert_stock: 8,
    status: "ACTIVE",
    price: 89.9,
    is_price_visible: true,
    tags: ["camisa", "polo", "western", "casual"],
    technical_specs: {
      material: "Piquet",
      manga: "Curta",
      tamanhos: "P ao GGG",
    },
    image: "/products/camisa-03.svg",
    created_at: "2025-02-01T10:00:00Z",
    updated_at: "2025-02-01T10:00:00Z",
  },
  {
    id: "p-020",
    idControl: "#CAMI0004",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camiseta Rodeio Estampada",
    title: "Camiseta Rodeio Estampada",
    subtitle: "Estampa exclusiva",
    description:
      "Camiseta com estampa exclusiva de rodeio em alta definição. T-shirt confortável e durável.",
    quantity: 100,
    alert_stock: 10,
    status: "ACTIVE",
    price: 69.9,
    is_price_visible: true,
    tags: ["camiseta", "rodeio", "estampada", "casual"],
    technical_specs: {
      material: "Algodão 100%",
      manga: "Curta",
      tamanhos: "P ao GG",
    },
    image: "/products/camisa-04.svg",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: "2025-02-15T10:00:00Z",
  },
  {
    id: "p-021",
    idControl: "#CAMI0005",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camisa Social Ranch",
    title: "Camisa Social Ranch",
    subtitle: "Slim fit premium",
    description:
      "Camisa social slim fit com toque country sutil. Para ocasiões que pedem mais elegância.",
    quantity: 25,
    alert_stock: 3,
    status: "ACTIVE",
    price: 179.9,
    is_price_visible: false,
    brand: "No Limite do Laço",
    tags: ["camisa", "social", "slim fit", "premium"],
    technical_specs: {
      material: "Tricoline",
      manga: "Longa",
      tamanhos: "P ao GG",
    },
    image: "/products/camisa-05.svg",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2025-03-01T10:00:00Z",
  },
  {
    id: "p-022",
    idControl: "#CAMI0006",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camisa Jeans Country",
    title: "Camisa Jeans Country",
    description:
      "Camisa jeans com lavagem country. O clássico que nunca sai de moda.",
    quantity: 40,
    alert_stock: 5,
    status: "ACTIVE",
    price: 139.9,
    is_price_visible: true,
    tags: ["camisa", "jeans", "country", "clássica"],
    technical_specs: {
      material: "Jeans leve",
      manga: "Longa",
      tamanhos: "P ao GGG",
    },
    image: "/products/camisa-06.svg",
    created_at: "2025-03-10T10:00:00Z",
    updated_at: "2025-03-10T10:00:00Z",
  },
  {
    id: "p-023",
    idControl: "#CAMI0007",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camisa Manga Curta Tropical",
    title: "Camisa Manga Curta Tropical Country",
    subtitle: "Verão country",
    description:
      "Camisa de manga curta com estampa tropical country. Leve e fresca para os dias quentes.",
    quantity: 50,
    alert_stock: 5,
    status: "ACTIVE",
    price: 99.9,
    is_price_visible: true,
    tags: ["camisa", "manga curta", "tropical", "verão"],
    technical_specs: {
      material: "Viscose",
      manga: "Curta",
      tamanhos: "P ao GG",
    },
    image: "/products/camisa-07.svg",
    created_at: "2025-03-15T10:00:00Z",
    updated_at: "2025-03-15T10:00:00Z",
  },
  {
    id: "p-024",
    idControl: "#CAMI0008",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camisa Infantil Country Stars",
    title: "Camisa Infantil Country Stars",
    subtitle: "Infantil unissex",
    description:
      "Camisa infantil country com estampa de estrelas. Confortável e divertida para crianças.",
    quantity: 70,
    alert_stock: 8,
    status: "ACTIVE",
    price: 59.9,
    is_price_visible: true,
    tags: ["camisa", "infantil", "stars", "unissex"],
    technical_specs: {
      material: "Algodão",
      manga: "Longa",
      tamanhos: "2 ao 14",
    },
    image: "/products/camisa-08.svg",
    created_at: "2025-03-20T10:00:00Z",
    updated_at: "2025-03-20T10:00:00Z",
  },
  // One INACTIVE product
  {
    id: "p-025",
    idControl: "#CAMI0009",
    company_id: "comp-01",
    catalog_id: "cat-01",
    category_id: "camisas",
    name: "Camisa Descontinuada Modelo Antigo",
    title: "Camisa Descontinuada Modelo Antigo",
    description: "Este modelo foi descontinuado.",
    quantity: 5,
    alert_stock: 1,
    status: "INACTIVE",
    price: 39.9,
    is_price_visible: false,
    tags: ["camisa", "descontinuada"],
    technical_specs: {},
    image: "/products/camisa-01.svg",
    created_at: "2024-06-01T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z",
  },
];

export function getActiveProducts(): Product[] {
  return MOCK_PRODUCTS.filter((p) => p.status === "ACTIVE");
}

export function getProductByIdControl(idControl: string): Product | undefined {
  return MOCK_PRODUCTS.find((p) => p.idControl === idControl);
}
